### ISSUE TITLE
ordering of analyses

### ISSUE THREAD

**Issue by garfieldnate** [hrzafer/nuve#72]
`Analyze` returns an `IList<Word>`, so an ordering on the returned analyses would be useful. The documentation does not say what order they are returned in, and until now I have simply used the first one.

One possibility would be to order them by length. For example, `başlamalısınız`:

    başlamalısınız için 4 çözüm bulundu:
    baş/ISIM lA/IY_FIIL_lA mA/FIILIMSI_ISIM_mA lU/IY_SIFAT_lU sUnUz/EKFIIL_SAHIS_SIZ_sUnUz
    baş/ISIM lA/IY_FIIL_lA mAlI/FC_KIP_GEREKLILIK_mAlI sUnUz/EKFIIL_SAHIS_SIZ_sUnUz
    başla/FIIL mA/FIILIMSI_ISIM_mA lU/IY_SIFAT_lU sUnUz/EKFIIL_SAHIS_SIZ_sUnUz
    başla/FIIL mAlI/FC_KIP_GEREKLILIK_mAlI sUnUz/EKFIIL_SAHIS_SIZ_sUnUz

I think the best analysis for this is the last one, which also has the fewest morphemes.

**Comment by hrzafer** [comment]
Ambiguity is always a problem for morphologic analysis of agglutinative languages like Turkish. For this example the second and the fourth ones are the more probable. But actually it depends on the context.  In fact 2. and 4. ones are equivalent. Because baş/ISIM lA/IY_FIIL_lA = başla/FIIL. Selecting the longest root with the least number of morphemes could be reasonable strategy.

But in reality, the only way is deciding the correct solution depending on previous and next words. And this requires some machine learning. I'm planning to add such a disambiguator module, maybe this summer.
