### ISSUE TITLE
Incorrect word analysis of arabalar

### ISSUE THREAD

**Issue by MonsterMMORPG** [hrzafer/nuve#83]
Nuve 1.5.2.0 from Nuget

![incorrecc](https://cloud.githubusercontent.com/assets/4149474/23797287/34a90fba-05b0-11e7-828c-5d06db1734ca.png)

**Comment by hrzafer** [comment]
Since the word `arap` exists as a noun in the dictionary the first analysis is correct. If you look up the TDK dictionary for the word you will see that both proper noun and noun types are possible for this word. 

However, the noun form seems obsolete to me. I'll consider removing it from the dictionary.
